name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Compile binary
        run: bun compile
      - name: Achieve built binary
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: dist/slide-merger
