name: release

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches:
      - "main"
  # push:
  #   tags:
  #     - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        run: echo "Release"
